import type { NextPage } from "next";
import Head from "next/head";
import estilos from "@estilos/Home.module.css";
import { Button } from "@mui/material";

const Home: NextPage = () => {
    return (
        <div className={estilos.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={estilos.main}>
                <Button variant="contained">Clique Aqui</Button>
                <h1 className={estilos.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={estilos.description}>
                    Get started by editing{" "}
                    <code className={estilos.code}>pages/index.tsx</code>
                </p>

                <div className={estilos.grid}>
                    <a href="https://nextjs.org/docs" className={estilos.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>
                    <a href="https://nextjs.org/learn" className={estilos.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>
                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={estilos.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>
                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=
                            default-template&utm_campaign=create-next-app"
                        className={estilos.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Ver-cel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={estilos.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-
                        template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={estilos.logo}>
                        <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
